//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangBanBanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangNhap
    {
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public int MANHANVIEN { get; set; }
        public Nullable<bool> XOA { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
