//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangBanBanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CT_Hoadon = new HashSet<CT_Hoadon>();
        }
    
        public int MAHOADON { get; set; }
        public System.DateTime DATECHECK { get; set; }
        public Nullable<System.DateTime> DATEOUT { get; set; }
        public Nullable<int> MANHANVIEN { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public Nullable<int> MABAN { get; set; }
        public bool TRANGTHAI { get; set; }
        public decimal TONGHOADON { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
    
        public virtual Ban Ban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_Hoadon> CT_Hoadon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
