//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangBanBanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CT_Hoadon = new HashSet<CT_Hoadon>();
        }
    
        public int MASANPHAM { get; set; }
        public int MADANHMUC { get; set; }
        public string TENSANPHAM { get; set; }
        public int SOLUONG { get; set; }
        public string MOTA { get; set; }
        public decimal DONGIA { get; set; }
        public Nullable<bool> XOA { get; set; }
        public byte[] HINHANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_Hoadon> CT_Hoadon { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
